spring:
  application:
    name: modulith.cqrs
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  modulith:
    events:
      completion-mode: archive
      republish-outstanding-events-on-restart: true


logging:
  level:
    gae.piaz.modulith.cqrs: DEBUG
    org.springframework.modulith: DEBUG
